### ISSUE TITLE
Does not work with the current release of `streaming-data-types`

### ISSUE THREAD

**Issue by nvaytet** [ess-dmsc/nexus-streamer-python#26]
When trying to start the Nexus streamer, I am getting the following error:
```
Traceback (most recent call last):
  File "/home/nvaytet/software/miniconda3/envs/scipp-developer/bin/nexus_streamer", line 5, in <module>
    from nexus_streamer.launch_nexus_streamer import launch_streamer
  File "/home/nvaytet/software/miniconda3/envs/scipp-developer/lib/python3.7/site-packages/nexus_streamer/launch_nexus_streamer.py", line 13, in <module>
    from .publish_run_message import (
  File "/home/nvaytet/software/miniconda3/envs/scipp-developer/lib/python3.7/site-packages/nexus_streamer/publish_run_message.py", line 1, in <module>
    from streaming_data_types.run_start_pl72 import serialise_pl72, DetectorSpectrumMap
ImportError: cannot import name 'DetectorSpectrumMap' from 'streaming_data_types.run_start_pl72' (/home/nvaytet/software/miniconda3/envs/scipp-developer/lib/python3.7/site-packages/streaming_data_types/run_start_pl72.py)
```

The current (conda) release of `nexus-streamer` seems to be incompatible with the current https://github.com/ess-dmsc/python-streaming-data-types (conda) release.
The workaround is to manually clone the https://github.com/ess-dmsc/python-streaming-data-types repo and add to `PYTHONPATH`.

**Comment by nvaytet** [comment]
This was due to an outdated (0.10) version of `streaming-data-types` installed in my local env.
Correctly installed v0.13 in a fresh conda env.
